#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 15 11:38:07 2022

@author: annajanuszyk
"""

import string

sentence = "Hello! This is an example."

for i in sentence:
    if i in string.punctuation:
        print("Punctuation: " + i)